name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment: { sdk: ^3.5.0 }

dependencies:
  flutter: { sdk: flutter }
  flutter_web_plugins: { sdk: flutter }
  carousel_slider_plus: { path: ../ }

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
