name: carousel_slider_plus
description: A carousel slider widget, support infinite scroll and custom child widget.
repository: https://github.com/kishan-dhankecha/carousel_slider_plus
version: 7.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0
